/**
 * Shipped defaults: theme tokens + per-locale UI strings.
 *
 * These reproduce this project's ORIGINAL hardcoded values, so a config that
 * omits `theme`/`ui` (or omits individual keys) renders byte-for-byte as before.
 * `loadConfig` merges authored values over these.
 *
 * UI strings are keyed by `site.lang`. Only the chrome strings users typically
 * want to rebrand are externalized here; the keyboard-shortcut cheatsheet labels
 * (`useKeyboardShortcuts.ts`) remain in code as an advanced concern.
 */

/** Default OKLCH theme tokens — mirror of `app/styles/tailwind.css` :root/.dark. */
export const DEFAULT_THEME = {
	light: {
		'--brand': 'oklch(0.42 0.158 286)',
		'--background': 'oklch(1 0 0)',
		'--foreground': 'oklch(0.145 0 0)',
		'--card': 'oklch(1 0 0)',
		'--card-foreground': 'oklch(0.145 0 0)',
		'--popover': 'oklch(1 0 0)',
		'--popover-foreground': 'oklch(0.145 0 0)',
		'--primary': 'var(--brand)',
		'--primary-foreground': 'oklch(0.985 0 0)',
		'--secondary': 'oklch(0.97 0 0)',
		'--secondary-foreground': 'oklch(0.205 0 0)',
		'--muted': 'oklch(0.97 0 0)',
		'--muted-foreground': 'oklch(0.556 0 0)',
		'--accent': 'oklch(0.97 0 0)',
		'--accent-foreground': 'oklch(0.205 0 0)',
		'--destructive': 'oklch(0.577 0.245 27.325)',
		'--border': 'oklch(0.922 0 0)',
		'--input': 'oklch(0.922 0 0)',
		'--ring': 'oklch(0.708 0 0)',
		'--sidebar': 'oklch(0.985 0 0)',
		'--sidebar-foreground': 'oklch(0.145 0 0)',
		'--sidebar-primary': 'oklch(0.205 0 0)',
		'--sidebar-primary-foreground': 'oklch(0.985 0 0)',
		'--sidebar-accent': 'oklch(0.97 0 0)',
		'--sidebar-accent-foreground': 'oklch(0.205 0 0)',
		'--sidebar-border': 'oklch(0.922 0 0)',
		'--sidebar-ring': 'oklch(0.708 0 0)',
	} as Record<string, string>,
	dark: {
		'--brand': 'oklch(0.68 0.14 286)',
		'--background': 'oklch(0.145 0 0)',
		'--foreground': 'oklch(0.985 0 0)',
		'--card': 'oklch(0.205 0 0)',
		'--card-foreground': 'oklch(0.985 0 0)',
		'--popover': 'oklch(0.205 0 0)',
		'--popover-foreground': 'oklch(0.985 0 0)',
		'--primary': 'var(--brand)',
		'--primary-foreground': 'oklch(0.205 0 0)',
		'--secondary': 'oklch(0.269 0 0)',
		'--secondary-foreground': 'oklch(0.985 0 0)',
		'--muted': 'oklch(0.269 0 0)',
		'--muted-foreground': 'oklch(0.708 0 0)',
		'--accent': 'oklch(0.269 0 0)',
		'--accent-foreground': 'oklch(0.985 0 0)',
		'--destructive': 'oklch(0.704 0.191 22.216)',
		'--border': 'oklch(1 0 0 / 10%)',
		'--input': 'oklch(1 0 0 / 15%)',
		'--ring': 'oklch(0.556 0 0)',
		'--sidebar': 'oklch(0.205 0 0)',
		'--sidebar-foreground': 'oklch(0.985 0 0)',
		'--sidebar-primary': 'oklch(0.488 0.243 264.376)',
		'--sidebar-primary-foreground': 'oklch(0.985 0 0)',
		'--sidebar-accent': 'oklch(0.269 0 0)',
		'--sidebar-accent-foreground': 'oklch(0.985 0 0)',
		'--sidebar-border': 'oklch(1 0 0 / 10%)',
		'--sidebar-ring': 'oklch(0.556 0 0)',
	} as Record<string, string>,
}

/**
 * The UI string catalogue. Keys are stable identifiers used in components via
 * `getUi(config)`; values are the originals (ru). `en` is a best-effort fallback
 * for non-ru sites so an unset `ui` doesn't render Russian on an English site.
 */
export const UI_STRINGS: Record<string, Record<string, string>> = {
	ru: {
		projects: 'Проекты',
		selectProject: 'Выберите проект',
		noProject: 'Без проекта',
		onThisPage: 'На этой странице',
		properties: 'Свойства',
		shortcuts: 'Горячие клавиши',
		searchProjectFilter: 'Проект',
		close: 'Закрыть',
		closePanel: 'Закрыть панель',
		closeSearch: 'Закрыть поиск',
		closeTab: 'Закрыть вкладку',
		home: 'Главная',
		files: 'Файлы',
		search: 'Поиск',
		toggleTheme: 'Переключить тему',
		// File-search (Ctrl/Cmd+P) in the sidebar
		fileSearchPlaceholder: 'Поиск по файлам...',
		fileSearch: 'Поиск по файлам',
		fileSearchHint: 'Поиск по файлам (Ctrl+P)',
		scopeAll: 'Все',
		scopeFiles: 'Файлы',
		scopeDirectories: 'Папки',
		nothingFound: 'Ничего не найдено',
		// Sidebar tree actions
		treeActions: 'Действия',
		resizePanel: 'Изменить ширину панели',
		locateInTree: 'Найти текущую страницу в дереве',
		locateInTreeHint: 'Найти в дереве (L)',
		collapseAll: 'Свернуть все папки',
		collapseAllHint: 'Свернуть всё (C)',
		openInNewTab: 'Открыть в новой вкладке (Shift+Enter)',
		expandRecursively: 'Развернуть рекурсивно (Shift+Enter)',
		// Content search (Ctrl/Cmd+K)
		searchDocs: 'Поиск по документации',
		searchDocsPlaceholder: 'Поиск по документации…',
		exactMatch: 'Точное совпадение',
		exactMatchHint: 'Точное совпадение фразы',
		clearSearch: 'Очистить поиск',
		clear: 'Очистить',
		searchIn: 'Искать в:',
		allProjects: 'Все проекты',
		wholeProject: 'весь проект',
		folder: 'Папка',
		folderPlaceholder: 'Папка (напр. требования/управление-клиентами)',
		clearFolder: 'Очистить папку',
		pickFolderFromTree: 'Выбрать папку из дерева',
		folderTree: 'Дерево папок',
		folderPicker: 'Выбор папки',
		typeToSearch: 'Введите запрос для поиска',
		loadingIndex: 'Загрузка индекса…',
		noResultsFor: 'Ничего не найдено по запросу',
		cancel: 'Отмена',
		ok: 'ОК',
		searchEllipsis: 'Поиск…',
		folderIn: 'Папка в',
		noSubfolders: 'В этом проекте нет вложенных папок',
		// Keyboard-shortcut cheatsheet: group display names + per-shortcut labels.
		groupNav: 'Навигация',
		groupTree: 'Дерево',
		groupTabs: 'Вкладки',
		scSearchContent: 'Поиск по содержимому',
		scShowShortcuts: 'Показать список горячих клавиш',
		scSearchFile: 'Поиск файла по имени',
		scLocate: 'Найти текущую страницу в дереве',
		scCollapseAll: 'Свернуть все папки',
		scCloseTab: 'Закрыть текущую вкладку',
		scShiftEnter: 'Файл — открыть в новой вкладке; папку — развернуть рекурсивно',
		// Misc chrome (Toc, mobile menus, code-wrap, find-on-page, tabs)
		noToc: 'Нет содержания',
		theme: 'Тема оформления',
		wrapLines: 'Переносить строки',
		noWrapLines: 'Не переносить строки',
		navigation: 'Навигация',
		pageActions: 'Действия страницы',
		scrollTop: 'Наверх',
		findOnPage: 'Найти на странице',
		findOnPagePlaceholder: 'Найти на странице…',
		toc: 'Содержание',
		hide: 'Скрыть',
		find: 'Найти',
		prevMatch: 'Предыдущее совпадение',
		nextMatch: 'Следующее совпадение',
		closeFindOnPage: 'Закрыть поиск по странице',
		closeTabHint: 'Закрыть (W)',
		tabActions: 'Действия с вкладками',
		closeAllTabs: 'Закрыть все вкладки',
	},
	en: {
		projects: 'Projects',
		selectProject: 'Select a project',
		noProject: 'No project',
		onThisPage: 'On this page',
		properties: 'Properties',
		shortcuts: 'Keyboard shortcuts',
		searchProjectFilter: 'Project',
		close: 'Close',
		closePanel: 'Close panel',
		closeSearch: 'Close search',
		closeTab: 'Close tab',
		home: 'Home',
		files: 'Files',
		search: 'Search',
		toggleTheme: 'Toggle theme',
		fileSearchPlaceholder: 'Search files...',
		fileSearch: 'Search files',
		fileSearchHint: 'Search files (Ctrl+P)',
		scopeAll: 'All',
		scopeFiles: 'Files',
		scopeDirectories: 'Folders',
		nothingFound: 'Nothing found',
		treeActions: 'Actions',
		resizePanel: 'Resize panel',
		locateInTree: 'Locate current page in the tree',
		locateInTreeHint: 'Locate in tree (L)',
		collapseAll: 'Collapse all folders',
		collapseAllHint: 'Collapse all (C)',
		openInNewTab: 'Open in a new tab (Shift+Enter)',
		expandRecursively: 'Expand recursively (Shift+Enter)',
		searchDocs: 'Search the docs',
		searchDocsPlaceholder: 'Search the docs…',
		exactMatch: 'Exact match',
		exactMatchHint: 'Exact phrase match',
		clearSearch: 'Clear search',
		clear: 'Clear',
		searchIn: 'Search in:',
		allProjects: 'All projects',
		wholeProject: 'whole project',
		folder: 'Folder',
		folderPlaceholder: 'Folder (e.g. guides/getting-started)',
		clearFolder: 'Clear folder',
		pickFolderFromTree: 'Pick a folder from the tree',
		folderTree: 'Folder tree',
		folderPicker: 'Folder picker',
		typeToSearch: 'Type to search',
		loadingIndex: 'Loading index…',
		noResultsFor: 'No results for',
		cancel: 'Cancel',
		ok: 'OK',
		searchEllipsis: 'Search…',
		folderIn: 'Folder in',
		noSubfolders: 'This project has no nested folders',
		groupNav: 'Navigation',
		groupTree: 'Tree',
		groupTabs: 'Tabs',
		scSearchContent: 'Search content',
		scShowShortcuts: 'Show keyboard shortcuts',
		scSearchFile: 'Find a file by name',
		scLocate: 'Locate current page in the tree',
		scCollapseAll: 'Collapse all folders',
		scCloseTab: 'Close current tab',
		scShiftEnter: 'File — open in a new tab; folder — expand recursively',
		noToc: 'No table of contents',
		theme: 'Theme',
		wrapLines: 'Wrap lines',
		noWrapLines: 'Don’t wrap lines',
		navigation: 'Navigation',
		pageActions: 'Page actions',
		scrollTop: 'Top',
		findOnPage: 'Find on page',
		findOnPagePlaceholder: 'Find on page…',
		toc: 'Contents',
		hide: 'Hide',
		find: 'Find',
		prevMatch: 'Previous match',
		nextMatch: 'Next match',
		closeFindOnPage: 'Close find on page',
		closeTabHint: 'Close (W)',
		tabActions: 'Tab actions',
		closeAllTabs: 'Close all tabs',
	},
}

/** UI strings for a language, falling back to `en` then `ru`. */
export function defaultUiFor(lang: string): Record<string, string> {
	return UI_STRINGS[lang] ?? UI_STRINGS.en ?? UI_STRINGS.ru
}
