/**
 * Serialize the resolved config for the running app.
 *
 * Emits two artifacts under the manifest dir (`app/generated`):
 * - `config.json` — the full resolved config (theme, ui, projects). Read at
 *   runtime via `fs` in `app/lib/config/config.server.ts`. Never imported, so it
 *   carries server-only detail (theme CSS tokens) safely.
 * - `site.ts` — a plain-literal module (client-safe subset) IMPORTED by the app,
 *   so Vite bundles projects/branding/ui strings into both client and server.
 *   This is what lets client components read projects synchronously.
 *
 * Per-project `landing` is defaulted here (not in `loadConfig`) because it needs
 * the compiled doc index: when a project doesn't pin a landing URL, we use the
 * first doc under that project as its landing page.
 */
import fs from 'node:fs/promises'
import path from 'node:path'

import type { DocsConfig } from '../app/lib/config/schema.ts'
import type { GeneratedSite, SiteProject } from '../app/lib/config/site.ts'

// Mirrors `GENERAL_PROJECT_ID` in app/lib/projects.ts. Inlined (not imported) so
// this build script never pulls in the app module, which imports the Vite-only
// `~/generated/site` alias that doesn't resolve under the plain-Node runner.
const GENERAL_PROJECT_ID = 'general'

interface IndexEntry {
	id: string
}

interface EmitArgs {
	config: DocsConfig
	manifestDir: string
	/** The doc index (already sorted), used to derive default landing URLs. */
	index: IndexEntry[]
	logger: { info(m: string): void }
}

/** The overridable slot names, in the order they appear in the generated module. */
const SLOT_NAMES = ['Home', 'DocPage', 'TopBar', 'Toc'] as const

/**
 * Render the generated `slots.ts`: import each configured override component by a
 * path relative to the manifest dir (so Vite resolves it from the user's
 * project), and export every slot as the override or `null` (= engine default).
 */
function renderSlots(components: Record<string, string | undefined>, manifestDir: string): string {
	const imports: string[] = []
	const exports: string[] = []
	for (const name of SLOT_NAMES) {
		const src = components[name]
		if (src) {
			// Resolve the user's path (relative to cwd) to an import specifier
			// relative to the manifest dir; ensure it starts with './' or '../'.
			let rel = path.relative(manifestDir, path.resolve(process.cwd(), src)).replace(/\\/g, '/')
			if (!rel.startsWith('.')) rel = `./${rel}`
			imports.push(`import ${name}Override from '${rel}'`)
			exports.push(`export const ${name} = ${name}Override`)
		} else {
			exports.push(`export const ${name}: ComponentType<any> | null = null`)
		}
	}
	return (
		`// AUTO-GENERATED by scripts/generate-content.ts — DO NOT EDIT.\n` +
		`import type { ComponentType } from 'react'\n` +
		(imports.length ? imports.join('\n') + '\n' : '') +
		`\n` +
		exports.join('\n') +
		`\n`
	)
}

/** Render the resolved theme token maps into a `:root` + `.dark` CSS block. */
function renderThemeCss(colors: { light: Record<string, string>; dark: Record<string, string> }): string {
	const block = (selector: string, vars: Record<string, string>) => {
		const lines = Object.entries(vars).map(([k, v]) => `\t${k}: ${v};`)
		return `${selector} {\n${lines.join('\n')}\n}`
	}
	return (
		`/* AUTO-GENERATED by scripts/generate-content.ts from docs.config.ts theme. DO NOT EDIT. */\n` +
		`${block(':root', colors.light)}\n\n` +
		`${block('.dark', colors.dark)}\n`
	)
}

/** First doc id whose project (first segment) is `projectId`, or null. */
function firstDocOfProject(index: IndexEntry[], projectId: string): string | null {
	for (const e of index) {
		if ((e.id.split('/')[0] ?? '') === projectId) return e.id
	}
	return null
}

/** First doc id that belongs to no known project (the general bucket), or null. */
function firstGeneralDoc(index: IndexEntry[], projectIds: Set<string>): string | null {
	for (const e of index) {
		if (!projectIds.has(e.id.split('/')[0] ?? '')) return e.id
	}
	return null
}

export async function emitGeneratedConfig({ config, manifestDir, index, logger }: EmitArgs): Promise<void> {
	const projectIds = new Set(config.projects.map((p) => p.id))

	// Resolve each project's landing URL: the authored value, else its first doc.
	const projects: SiteProject[] = config.projects.map((p) => {
		const first = firstDocOfProject(index, p.id)
		const landing = p.landing ?? (first ? `/${first}/` : '/')
		return {
			id: p.id,
			name: p.name,
			logo: p.logo ?? `/projects/${p.id}.svg`,
			landing,
			description: p.description,
		}
	})

	const generalHasDocs = config.general.enabled && firstGeneralDoc(index, projectIds) !== null
	const site: GeneratedSite = {
		site: {
			title: config.site.title,
			description: config.site.description,
			lang: config.site.lang,
			favicon: config.site.favicon,
			logo: config.site.logo,
			defaultTheme: config.site.defaultTheme,
		},
		projects,
		general: {
			enabled: generalHasDocs,
			id: GENERAL_PROJECT_ID,
			name: config.general.name,
			logo: config.general.logo,
			description: config.general.description,
		},
		ui: config.ui,
	}

	// Full config (server-only) — includes resolved landings so the server agrees
	// with the client `site.ts` view.
	const fullConfig = { ...config, projects: config.projects.map((p, i) => ({ ...p, landing: projects[i].landing })) }
	await fs.writeFile(path.join(manifestDir, 'config.json'), JSON.stringify(fullConfig))

	// Client-safe literals module. Pretty-printed so a human can diff it.
	const siteModule =
		`// AUTO-GENERATED by scripts/generate-content.ts — DO NOT EDIT.\n` +
		`import type { GeneratedSite } from '~/lib/config/site'\n\n` +
		`export const SITE: GeneratedSite = ${JSON.stringify(site, null, '\t')}\n`
	await fs.writeFile(path.join(manifestDir, 'site.ts'), siteModule)

	// Theme CSS: the resolved theme already has defaults merged with the user's
	// overrides, so emit the full :root/.dark token blocks. Imported AFTER
	// tailwind.css in root.tsx, so these win; the `--sl-*` bridge in tailwind.css
	// (which references these vars) keeps generated markdown tracking the theme.
	await fs.writeFile(path.join(manifestDir, 'theme.generated.css'), renderThemeCss(config.theme.colors))

	// Slot overrides: rewrite the generated slots module to import any user
	// override components (by path, resolved from the user's project) and fall the
	// rest back to null (= engine default). See app/lib/slots.tsx.
	await fs.writeFile(path.join(manifestDir, 'slots.ts'), renderSlots(config.components, manifestDir))

	logger.info(`Emitted config.json + site.ts + theme.generated.css + slots.ts (${projects.length} project(s)${generalHasDocs ? ' + general' : ''}).`)
}
